// Content for each /services/[slug] page. Placeholder copy — refine before launch.
export const services = [
  {
    slug: "landing-pages",
    icon: "landing",
    en: {
      title: "Landing Pages",
      summary: "A focused, high-converting page for your product, offer or event. Perfect for Facebook ad campaigns.",
      tagline: "One focused page that turns visitors into customers.",
      intro:
        "A landing page has one job: get your visitor to take action message you, call you or place an order. We design clean, fast pages around a single goal, perfect for Facebook and Google ad campaigns, product launches, events and special offers.",
      price: "৳1,500 – ৳5,000",
      time: "3–7 days",
      features: [
        { title: "Conversion-focused layout", desc: "Every section leads the visitor towards your main call to action." },
        { title: "Mobile-first design", desc: "Looks and works perfectly on phones, where most of your ad traffic comes from." },
        { title: "WhatsApp & call buttons", desc: "Visitors can reach you in one tap, straight from the page." },
        { title: "Fast loading", desc: "Optimised images and code so the page opens quickly even on slow connections." },
        { title: "Facebook Pixel ready", desc: "We can add Meta Pixel and Google Analytics so you can measure your ads." },
        { title: "Basic SEO", desc: "Proper titles, descriptions and social sharing previews." },
      ],
      idealFor: ["Product launches", "Facebook ad campaigns", "Events & workshops", "Special offers & sales", "Course enrolment", "App downloads"],
      faq: [
        { q: "Can I use my own domain?", a: "Yes. We connect the page to your domain, or help you buy one." },
        { q: "Can you add an order form?", a: "Yes, a simple order or lead form can be added, sending submissions to your email or WhatsApp." },
        { q: "How many sections are included?", a: "Up to 6 sections in the base package. More can be added for a small fee." },
      ],
    },
    bn: {
      title: "ল্যান্ডিং পেজ",
      summary: "আপনার পণ্য, অফার বা ইভেন্টের জন্য একটা কার্যকর পেজ। Facebook বিজ্ঞাপনের জন্য একদম উপযুক্ত।",
      tagline: "একটা কার্যকর পেজ, যা ভিজিটরকে কাস্টমারে পরিণত করে।",
      intro:
        "ল্যান্ডিং পেজের কাজ একটাই: ভিজিটরকে দিয়ে একটা কাজ করানো মেসেজ দেওয়া, কল করা বা অর্ডার করা। আমরা একটা নির্দিষ্ট লক্ষ্য মাথায় রেখে পরিষ্কার ও দ্রুত পেজ ডিজাইন করি — Facebook ও Google বিজ্ঞাপন, নতুন পণ্য, ইভেন্ট ও বিশেষ অফারের জন্য একদম উপযুক্ত।",
      price: "৳১,৫০০ – ৳৫,০০০",
      time: "৩–৭ দিন",
      features: [
        { title: "কনভার্সন-কেন্দ্রিক লেআউট", desc: "প্রতিটা সেকশন ভিজিটরকে আপনার মূল বাটনের দিকে নিয়ে যায়।" },
        { title: "মোবাইল-ফার্স্ট ডিজাইন", desc: "বিজ্ঞাপনের বেশিরভাগ ভিজিটর মোবাইল থেকে আসে, তাই মোবাইলে নিখুঁত দেখায়।" },
        { title: "WhatsApp ও কল বাটন", desc: "এক ট্যাপেই ভিজিটর আপনার সাথে যোগাযোগ করতে পারবে।" },
        { title: "দ্রুত লোডিং", desc: "অপটিমাইজড ছবি ও কোড, তাই ধীর ইন্টারনেটেও দ্রুত খোলে।" },
        { title: "Facebook Pixel রেডি", desc: "বিজ্ঞাপনের ফলাফল মাপতে Meta Pixel ও Google Analytics যোগ করা যায়।" },
        { title: "বেসিক SEO", desc: "সঠিক টাইটেল, বিবরণ আর সোশ্যাল মিডিয়ায় শেয়ারের প্রিভিউ।" },
      ],
      idealFor: ["নতুন পণ্য লঞ্চ", "Facebook বিজ্ঞাপন", "ইভেন্ট ও ওয়ার্কশপ", "বিশেষ অফার ও সেল", "কোর্সে ভর্তি", "অ্যাপ ডাউনলোড"],
      faq: [
        { q: "নিজের ডোমেইন ব্যবহার করা যাবে?", a: "হ্যাঁ। আপনার ডোমেইনে পেজটা যুক্ত করে দেওয়া হবে, অথবা ডোমেইন কিনতে সাহায্য করা হবে।" },
        { q: "অর্ডার ফর্ম যোগ করা যাবে?", a: "হ্যাঁ, একটা সহজ অর্ডার বা যোগাযোগ ফর্ম যোগ করা যায়, যা আপনার ইমেইল বা WhatsApp-এ পৌঁছাবে।" },
        { q: "কয়টা সেকশন থাকবে?", a: "বেসিক প্যাকেজে সর্বোচ্চ ৬টা সেকশন। অল্প খরচে আরও যোগ করা যায়।" },
      ],
    },
  },
  {
    slug: "portfolio-websites",
    icon: "portfolio",
    en: {
      title: "Portfolio Websites",
      summary: "Show your work beautifully for photographers, designers, freelancers, doctors and professionals.",
      tagline: "Show your work beautifully and win better clients.",
      intro:
        "Your portfolio is often the first impression a client gets. We build elegant personal websites that put your work front and centre for photographers, designers, architects, freelancers, doctors, lawyers and other professionals.",
      price: "৳1,500 – ৳5,000",
      time: "3–7 days",
      features: [
        { title: "Beautiful project gallery", desc: "Grid or masonry galleries with full-screen image viewing." },
        { title: "About & services pages", desc: "Tell your story and explain what you offer clearly." },
        { title: "Contact & booking", desc: "Contact form, WhatsApp button and optional booking link." },
        { title: "Easy updates", desc: "Add new projects yourself without touching any code." },
        { title: "Social links", desc: "Connect your Facebook, Instagram, LinkedIn, Behance and more." },
        { title: "Personal domain", desc: "A professional yourname.com address that builds trust." },
      ],
      idealFor: ["Photographers", "Graphic designers", "Architects", "Freelancers", "Doctors & consultants", "Artists & writers"],
      faq: [
        { q: "How many projects can I show?", a: "As many as you like. The gallery grows as you add new work." },
        { q: "Can I add a blog?", a: "Yes, a simple blog can be added as an extra page." },
        { q: "Do you help with the content?", a: "We guide you on what to include, and can polish your text for a small fee." },
      ],
    },
    bn: {
      title: "পোর্টফোলিও ওয়েবসাইট",
      summary: "ফটোগ্রাফার, ডিজাইনার, ফ্রিল্যান্সার, ডাক্তার ও পেশাজীবীদের কাজ সুন্দরভাবে তুলে ধরার জন্য।",
      tagline: "আপনার কাজ সুন্দরভাবে দেখান, ভালো ক্লায়েন্ট পান।",
      intro:
        "ক্লায়েন্ট প্রথম যা দেখে, তা প্রায়ই আপনার পোর্টফোলিও। আমরা এমন রুচিশীল ব্যক্তিগত ওয়েবসাইট বানাই যেখানে আপনার কাজই থাকে কেন্দ্রে ফটোগ্রাফার, ডিজাইনার, আর্কিটেক্ট, ফ্রিল্যান্সার, ডাক্তার, আইনজীবী ও অন্যান্য পেশাজীবীদের জন্য।",
      price: "৳১,৫০০ – ৳৫,০০০",
      time: "৩–৭ দিন",
      features: [
        { title: "সুন্দর প্রজেক্ট গ্যালারি", desc: "গ্রিড বা ম্যাসনরি গ্যালারি, ফুল স্ক্রিনে ছবি দেখার সুবিধাসহ।" },
        { title: "পরিচিতি ও সার্ভিস পেজ", desc: "আপনার গল্প আর আপনি কী অফার করেন তা পরিষ্কারভাবে তুলে ধরুন।" },
        { title: "যোগাযোগ ও বুকিং", desc: "কন্টাক্ট ফর্ম, WhatsApp বাটন আর চাইলে বুকিং লিংক।" },
        { title: "সহজ আপডেট", desc: "কোড ছাড়াই নিজে নতুন প্রজেক্ট যোগ করতে পারবেন।" },
        { title: "সোশ্যাল লিংক", desc: "Facebook, Instagram, LinkedIn, Behance ইত্যাদি যুক্ত করুন।" },
        { title: "নিজস্ব ডোমেইন", desc: "yourname.com এর মতো পেশাদার ঠিকানা, যা বিশ্বাস তৈরি করে।" },
      ],
      idealFor: ["ফটোগ্রাফার", "গ্রাফিক ডিজাইনার", "আর্কিটেক্ট", "ফ্রিল্যান্সার", "ডাক্তার ও কনসালট্যান্ট", "শিল্পী ও লেখক"],
      faq: [
        { q: "কতগুলো প্রজেক্ট দেখানো যাবে?", a: "যত খুশি। নতুন কাজ যোগ করলে গ্যালারি বাড়তে থাকবে।" },
        { q: "ব্লগ যোগ করা যাবে?", a: "হ্যাঁ, অতিরিক্ত পেজ হিসেবে একটা সহজ ব্লগ যোগ করা যায়।" },
        { q: "কন্টেন্টে সাহায্য করবেন?", a: "কী কী রাখবেন সে বিষয়ে গাইড করা হবে, আর অল্প খরচে লেখা ঘষামাজা করে দেওয়া যায়।" },
      ],
    },
  },
  {
    slug: "business-websites",
    icon: "business",
    en: {
      title: "Business Websites",
      summary: "Multi-page sites for shops, restaurants, clinics, coaching centres and companies.",
      tagline: "A complete online home for your business.",
      intro:
        "A professional website makes your business look trustworthy and helps customers find you on Google. We build multi-page websites for shops, restaurants, clinics, coaching centres, schools and companies easy for you to update and easy for customers to use.",
      price: "৳5,000 – ৳50,000",
      time: "7–30 days",
      features: [
        { title: "Up to 8 pages", desc: "Home, about, services, gallery, team, contact and more." },
        { title: "Google Map & location", desc: "Customers can find your shop or office in one tap." },
        { title: "Easy content editing", desc: "Update text, prices and photos yourself from a simple panel." },
        { title: "SEO optimisation", desc: "Structured so Google understands your business and services." },
        { title: "WhatsApp chat", desc: "A floating chat button so customers can message you instantly." },
        { title: "Speed & security", desc: "SSL certificate, fast hosting setup and regular backups." },
      ],
      idealFor: ["Restaurants & cafés", "Clinics & hospitals", "Coaching centres & schools", "Retail shops", "Real estate", "Small companies"],
      faq: [
        { q: "Can customers book or order online?", a: "Yes. Booking forms, menus and simple ordering can be added based on your needs." },
        { q: "Will it show up on Google?", a: "We set up the basics for Google and submit your site. Ranking higher takes time and regular content." },
        { q: "Can it be in Bangla?", a: "Yes Bangla, English, or both with a language switch like this site." },
      ],
    },
    bn: {
      title: "বিজনেস ওয়েবসাইট",
      summary: "দোকান, রেস্টুরেন্ট, ক্লিনিক, কোচিং সেন্টার ও কোম্পানির জন্য একাধিক পেজের ওয়েবসাইট।",
      tagline: "আপনার ব্যবসার পূর্ণাঙ্গ অনলাইন ঠিকানা।",
      intro:
        "একটা পেশাদার ওয়েবসাইট আপনার ব্যবসাকে বিশ্বাসযোগ্য করে তোলে আর Google-এ কাস্টমারদের আপনাকে খুঁজে পেতে সাহায্য করে। আমরা দোকান, রেস্টুরেন্ট, ক্লিনিক, কোচিং সেন্টার, স্কুল ও কোম্পানির জন্য একাধিক পেজের ওয়েবসাইট বানাই যা আপনার জন্য আপডেট করা সহজ, কাস্টমারের জন্য ব্যবহার করা সহজ।",
      price: "৳৫,০০০ – ৳৫০,০০০",
      time: "৭–৩০ দিন",
      features: [
        { title: "সর্বোচ্চ ৮টি পেজ", desc: "হোম, পরিচিতি, সার্ভিস, গ্যালারি, টিম, যোগাযোগ ও আরও।" },
        { title: "Google Map ও লোকেশন", desc: "এক ট্যাপেই কাস্টমার আপনার দোকান বা অফিস খুঁজে পাবে।" },
        { title: "সহজে কন্টেন্ট এডিট", desc: "সহজ প্যানেল থেকে নিজেই লেখা, দাম ও ছবি বদলাতে পারবেন।" },
        { title: "SEO অপটিমাইজেশন", desc: "এমনভাবে সাজানো যাতে Google আপনার ব্যবসা ও সার্ভিস বুঝতে পারে।" },
        { title: "WhatsApp চ্যাট", desc: "ভাসমান চ্যাট বাটন, যাতে কাস্টমার সাথে সাথে মেসেজ দিতে পারে।" },
        { title: "স্পিড ও নিরাপত্তা", desc: "SSL সার্টিফিকেট, দ্রুত হোস্টিং সেটআপ আর নিয়মিত ব্যাকআপ।" },
      ],
      idealFor: ["রেস্টুরেন্ট ও ক্যাফে", "ক্লিনিক ও হাসপাতাল", "কোচিং সেন্টার ও স্কুল", "দোকান ও শোরুম", "রিয়েল এস্টেট", "ছোট কোম্পানি"],
      faq: [
        { q: "কাস্টমার কি অনলাইনে বুকিং বা অর্ডার করতে পারবে?", a: "হ্যাঁ। আপনার প্রয়োজন অনুযায়ী বুকিং ফর্ম, মেনু ও সহজ অর্ডার সিস্টেম যোগ করা যায়।" },
        { q: "Google-এ দেখাবে?", a: "Google-এর জন্য বেসিক সেটআপ করে সাইট সাবমিট করা হবে। উপরের দিকে আসতে সময় ও নিয়মিত কন্টেন্ট লাগে।" },
        { q: "বাংলায় করা যাবে?", a: "হ্যাঁ — বাংলা, ইংরেজি, অথবা এই সাইটের মতো ভাষা পরিবর্তনের সুবিধাসহ দুটোই।" },
      ],
    },
  },
  {
    slug: "web-applications",
    icon: "webapp",
    en: {
      title: "Web Applications",
      summary: "Custom dashboards, booking systems and admin panels built with modern technology.",
      tagline: "Custom software that runs your business smarter.",
      intro:
        "When a simple website isn't enough, we build web applications tailored to how your business works booking systems, admin dashboards, inventory and order management, student portals and more. Built with modern technology like Next.js and React.",
      price: "৳5,000 – ৳50,000",
      time: "7–30 days",
      features: [
        { title: "Custom dashboards", desc: "See sales, bookings and key numbers at a glance." },
        { title: "User accounts & roles", desc: "Secure login for admins, staff and customers with the right permissions." },
        { title: "Booking & scheduling", desc: "Online appointments with time slots and reminders." },
        { title: "Payment integration", desc: "Accept payments through bKash, Nagad, SSLCommerz and cards." },
        { title: "Reports & exports", desc: "Download data as Excel or PDF whenever you need it." },
        { title: "Scalable architecture", desc: "Built to grow with your business, not hold it back." },
      ],
      idealFor: ["Booking systems", "Admin panels", "Inventory management", "School & coaching portals", "Order management", "Internal tools"],
      faq: [
        { q: "How is the price decided?", a: "It depends on features. After a short call we send a detailed scope with a fixed price." },
        { q: "Do I own the source code?", a: "Yes. The full source code is handed over to you after final payment." },
        { q: "Do you provide support after launch?", a: "Yes, 30 days free support, then optional monthly maintenance plans." },
      ],
    },
    bn: {
      title: "ওয়েব অ্যাপ্লিকেশন",
      summary: "আধুনিক প্রযুক্তিতে বানানো ড্যাশবোর্ড, বুকিং সিস্টেম ও অ্যাডমিন প্যানেল।",
      tagline: "কাস্টম সফটওয়্যার, যা আপনার ব্যবসাকে আরও স্মার্ট করে।",
      intro:
        "যখন সাধারণ ওয়েবসাইট যথেষ্ট না, তখন আপনার ব্যবসার কাজের ধরন অনুযায়ী ওয়েব অ্যাপ্লিকেশন বানানো হয় বুকিং সিস্টেম, অ্যাডমিন ড্যাশবোর্ড, ইনভেন্টরি ও অর্ডার ম্যানেজমেন্ট, স্টুডেন্ট পোর্টাল ইত্যাদি। Next.js ও React-এর মতো আধুনিক প্রযুক্তিতে তৈরি।",
      price: "৳৫,০০০ – ৳৫০,০০০",
      time: "৭–৩০ দিন",
      features: [
        { title: "কাস্টম ড্যাশবোর্ড", desc: "বিক্রি, বুকিং আর গুরুত্বপূর্ণ সংখ্যা এক নজরে দেখুন।" },
        { title: "ইউজার অ্যাকাউন্ট ও রোল", desc: "অ্যাডমিন, স্টাফ ও কাস্টমারের জন্য নিরাপদ লগইন ও আলাদা অনুমতি।" },
        { title: "বুকিং ও শিডিউলিং", desc: "টাইম স্লট ও রিমাইন্ডারসহ অনলাইন অ্যাপয়েন্টমেন্ট।" },
        { title: "পেমেন্ট ইন্টিগ্রেশন", desc: "bKash, Nagad, SSLCommerz ও কার্ডে পেমেন্ট নিন।" },
        { title: "রিপোর্ট ও এক্সপোর্ট", desc: "যখন দরকার Excel বা PDF আকারে ডেটা ডাউনলোড করুন।" },
        { title: "স্কেলেবল কাঠামো", desc: "ব্যবসা বড় হলে সিস্টেমও সাথে বাড়বে।" },
      ],
      idealFor: ["বুকিং সিস্টেম", "অ্যাডমিন প্যানেল", "ইনভেন্টরি ম্যানেজমেন্ট", "স্কুল ও কোচিং পোর্টাল", "অর্ডার ম্যানেজমেন্ট", "অফিসের নিজস্ব টুল"],
      faq: [
        { q: "দাম কীভাবে ঠিক হয়?", a: "ফিচারের ওপর নির্ভর করে। ছোট একটা আলাপের পর নির্দিষ্ট দামসহ বিস্তারিত স্কোপ পাঠানো হয়।" },
        { q: "সোর্স কোডের মালিক কি আমি?", a: "হ্যাঁ। শেষ পেমেন্টের পর পুরো সোর্স কোড আপনাকে দেওয়া হয়।" },
        { q: "লঞ্চের পর সাপোর্ট দেন?", a: "হ্যাঁ, ৩০ দিন ফ্রি সাপোর্ট, এরপর চাইলে মাসিক মেইনটেন্যান্স প্ল্যান।" },
      ],
    },
  },
  {
    slug: "mobile-apps",
    icon: "mobile",
    en: {
      title: "Mobile Apps",
      summary: "Android and iOS apps for your business, published under your own store account.",
      tagline: "Your business in your customers' pocket.",
      intro:
        "We build Android and iOS apps from a single codebase using Flutter or React Native, keeping cost low and quality high. Your app is published under your own Play Store and App Store account, so you stay in full control.",
      price: "৳5,000 – ৳50,000",
      time: "7–30 days",
      features: [
        { title: "Android & iOS", desc: "One codebase, two platforms saving you time and money." },
        { title: "Clean, native feel", desc: "Smooth animations and familiar patterns your users already know." },
        { title: "Push notifications", desc: "Send offers, reminders and updates directly to users' phones." },
        { title: "Login & profiles", desc: "Phone, email or Google sign-in with user profiles." },
        { title: "Payments", desc: "Integrate bKash, Nagad and other local payment gateways." },
        { title: "Store publishing", desc: "We handle the Play Store and App Store submission for you." },
      ],
      idealFor: ["E-commerce shops", "Delivery services", "Education apps", "Booking & appointments", "Community apps", "Companion apps for websites"],
      faq: [
        { q: "Do I need a developer account?", a: "Yes — a Google Play account (one-time fee) and, for iOS, an Apple Developer account (yearly fee). We help you set them up." },
        { q: "Can my website and app share data?", a: "Yes. We can build a shared backend so your website and app stay in sync." },
        { q: "What about updates?", a: "Bug fixes are free for 30 days. New features and OS updates are covered by maintenance plans." },
      ],
    },
    bn: {
      title: "মোবাইল অ্যাপ",
      summary: "আপনার ব্যবসার জন্য Android ও iOS অ্যাপ, আপনার নিজের স্টোর অ্যাকাউন্টে প্রকাশিত।",
      tagline: "আপনার ব্যবসা, কাস্টমারের পকেটে।",
      intro:
        "Flutter বা React Native দিয়ে একটা কোডবেস থেকেই Android ও iOS অ্যাপ বানানো হয় তাই খরচ কম, মান ভালো। অ্যাপটা আপনার নিজের Play Store ও App Store অ্যাকাউন্টে প্রকাশ করা হয়, তাই নিয়ন্ত্রণ পুরোপুরি আপনার হাতে।",
      price: "৳৫,০০০ – ৳৫০,০০০",
      time: "৭–৩০ দিন",
      features: [
        { title: "Android ও iOS", desc: "একটা কোডবেস, দুটো প্ল্যাটফর্ম সময় ও খরচ দুটোই বাঁচে।" },
        { title: "পরিষ্কার, স্বাভাবিক অনুভূতি", desc: "মসৃণ অ্যানিমেশন আর ইউজারদের পরিচিত ডিজাইন।" },
        { title: "পুশ নোটিফিকেশন", desc: "অফার, রিমাইন্ডার ও আপডেট সরাসরি ইউজারের ফোনে পাঠান।" },
        { title: "লগইন ও প্রোফাইল", desc: "ফোন, ইমেইল বা Google দিয়ে সাইন-ইন ও ইউজার প্রোফাইল।" },
        { title: "পেমেন্ট", desc: "bKash, Nagad ও অন্যান্য লোকাল পেমেন্ট গেটওয়ে যুক্ত করুন।" },
        { title: "স্টোরে প্রকাশ", desc: "Play Store ও App Store-এ সাবমিট করার কাজ আমরাই করি।" },
      ],
      idealFor: ["ই-কমার্স শপ", "ডেলিভারি সার্ভিস", "শিক্ষামূলক অ্যাপ", "বুকিং ও অ্যাপয়েন্টমেন্ট", "কমিউনিটি অ্যাপ", "ওয়েবসাইটের সাথী অ্যাপ"],
      faq: [
        { q: "ডেভেলপার অ্যাকাউন্ট লাগবে?", a: "হ্যাঁ  Google Play অ্যাকাউন্ট (এককালীন ফি) আর iOS-এর জন্য Apple Developer অ্যাকাউন্ট (বাৎসরিক ফি)। সেটআপে সাহায্য করা হবে।" },
        { q: "ওয়েবসাইট আর অ্যাপ কি একই ডেটা ব্যবহার করতে পারবে?", a: "হ্যাঁ। একটা শেয়ার্ড ব্যাকএন্ড বানানো যায়, যাতে ওয়েবসাইট ও অ্যাপ সবসময় মিলে থাকে।" },
        { q: "আপডেটের কী হবে?", a: "৩০ দিন বাগ ফিক্স ফ্রি। নতুন ফিচার ও OS আপডেট মেইনটেন্যান্স প্ল্যানে কাভার করা হয়।" },
      ],
    },
  },
  {
    slug: "hosting-care",
    icon: "hosting",
    en: {
      title: "Hosting & Care",
      summary: "Domain, hosting, SSL, backups and small updates we keep your site running so you don't have to.",
      tagline: "We keep your website fast, safe and online.",
      intro:
        "Don't want to deal with servers, renewals and updates? Our Hosting & Care plan takes care of everything technical, so you can focus on your business. Your domain stays in your name, and you can move your site anytime.",
      price: "৳3,000 / year",
      time: "Setup in 1 day",
      features: [
        { title: "Fast, reliable hosting", desc: "Your site runs on quality servers with high uptime." },
        { title: "Free SSL certificate", desc: "The padlock icon and https:// that customers and Google trust." },
        { title: "Daily backups", desc: "If anything goes wrong, we can restore your site quickly." },
        { title: "Domain renewal reminders", desc: "Never lose your domain because of a missed renewal." },
        { title: "Small monthly updates", desc: "Text, price or photo changes included every month." },
        { title: "Uptime monitoring", desc: "We get alerted if your site goes down and fix it fast." },
      ],
      idealFor: ["Busy business owners", "Sites we built for you", "Existing sites needing care", "Anyone who hates tech hassle"],
      faq: [
        { q: "Can I move my site later?", a: "Yes, anytime. We hand over all files and help with the move." },
        { q: "Can you host a site you didn't build?", a: "Usually yes. We review it first to check it's in good shape." },
        { q: "What counts as a small update?", a: "Changing text, prices, photos or contact details. New pages or features are quoted separately." },
      ],
    },
    bn: {
      title: "হোস্টিং ও মেইনটেন্যান্স",
      summary: "ডোমেইন, হোস্টিং, SSL, ব্যাকআপ আর ছোটখাটো আপডেট — আপনার সাইট সচল রাখার দায়িত্ব আমাদের।",
      tagline: "আপনার ওয়েবসাইট দ্রুত, নিরাপদ ও সচল রাখার দায়িত্ব আমাদের।",
      intro:
        "সার্ভার, রিনিউয়াল আর আপডেটের ঝামেলায় যেতে চান না? আমাদের হোস্টিং ও মেইনটেন্যান্স প্ল্যানে সব টেকনিক্যাল কাজ আমরাই সামলাই, আপনি ব্যবসায় মন দিন। ডোমেইন আপনার নামেই থাকবে, আর যেকোনো সময় সাইট সরিয়ে নিতে পারবেন।",
      price: "৳৩,০০০ / বছর",
      time: "১ দিনে সেটআপ",
      features: [
        { title: "দ্রুত ও নির্ভরযোগ্য হোস্টিং", desc: "ভালো মানের সার্ভারে আপনার সাইট সবসময় সচল থাকবে।" },
        { title: "ফ্রি SSL সার্টিফিকেট", desc: "তালার চিহ্ন আর https://, যা কাস্টমার ও Google বিশ্বাস করে।" },
        { title: "প্রতিদিন ব্যাকআপ", desc: "কোনো সমস্যা হলে দ্রুত সাইট আগের অবস্থায় ফেরানো যায়।" },
        { title: "ডোমেইন রিনিউয়াল রিমাইন্ডার", desc: "রিনিউ করতে ভুলে গিয়ে ডোমেইন হারানোর ভয় নেই।" },
        { title: "মাসিক ছোট আপডেট", desc: "প্রতি মাসে লেখা, দাম বা ছবি পরিবর্তন অন্তর্ভুক্ত।" },
        { title: "আপটাইম মনিটরিং", desc: "সাইট বন্ধ হলে আমরা সাথে সাথে জানতে পারি এবং ঠিক করি।" },
      ],
      idealFor: ["ব্যস্ত ব্যবসায়ী", "আমাদের বানানো সাইট", "পুরোনো সাইটের দেখাশোনা", "যারা টেকনিক্যাল ঝামেলা পছন্দ করেন না"],
      faq: [
        { q: "পরে কি সাইট অন্য জায়গায় সরাতে পারব?", a: "হ্যাঁ, যেকোনো সময়। সব ফাইল দিয়ে দেওয়া হবে এবং সরাতে সাহায্য করা হবে।" },
        { q: "অন্যের বানানো সাইট হোস্ট করবেন?", a: "সাধারণত হ্যাঁ। আগে একবার দেখে নেওয়া হয় সাইটটা ঠিকঠাক আছে কিনা।" },
        { q: "ছোট আপডেট বলতে কী বোঝায়?", a: "লেখা, দাম, ছবি বা যোগাযোগের তথ্য পরিবর্তন। নতুন পেজ বা ফিচারের দাম আলাদা।" },
      ],
    },
  },
];

export const getService = (slug) => services.find((s) => s.slug === slug);
